-- Datos de catálogo: sucursales, categorías y puntos de checklist con sus pesos.
-- Generado a partir de DASHBOARD EDIFICIOS.xlsx (hojas Hoja1/Hoja2).
-- NOTA: el Excel de origen contiene 25 sucursales (no 26); agrega/edita filas aquí si falta alguna.

insert into branches (code, name) values
  ('BJX', 'BJX'),
  ('CCA', 'CCA'),
  ('CEN', 'CEN'),
  ('CLN', 'CLN'),
  ('CSL', 'CSL'),
  ('ENS', 'ENS'),
  ('GDL', 'GDL'),
  ('GML', 'GML'),
  ('GSV', 'GSV'),
  ('GYM', 'GYM'),
  ('HMO', 'HMO'),
  ('IZT', 'IZT'),
  ('LAP', 'LAP'),
  ('LMM', 'LMM'),
  ('MEX', 'MEX'),
  ('MXL', 'MXL'),
  ('MZT', 'MZT'),
  ('NJA', 'NJA'),
  ('NOG', 'NOG'),
  ('PBC', 'PBC'),
  ('QRO', 'QRO'),
  ('SLR', 'SLR'),
  ('TIJ', 'TIJ'),
  ('TPQ', 'TPQ'),
  ('ZAP', 'ZAP');

insert into categories (name, sort_order) values
  ('LIMPIEZA', 0),
  ('PINTURA', 1),
  ('MOB', 2),
  ('ILUMINACION', 3),
  ('PLOMERIA', 4),
  ('EDIFICIO', 5),
  ('LETREROS', 6),
  ('SEGURIDAD', 7),
  ('LOGO', 8),
  ('PERSONAL', 9);

insert into checklist_items (category_id, description, weight, sort_order) values
  ((select id from categories where name = 'LIMPIEZA'), 'Piso barrido/trapeado en las áreas visibles (oficinas, bodega, sanitarios)', 0.4, 0),
  ((select id from categories where name = 'LIMPIEZA'), 'Sanitarios limpios y desinfectados, sin malos olores', 0.3, 1),
  ((select id from categories where name = 'LIMPIEZA'), 'Bodega ordenada, sin acumulación de cajas/tarimas', 0.1, 2),
  ((select id from categories where name = 'LIMPIEZA'), 'Exteriores (patio, estacionamiento, accesos) libre de basura, maleza o materiales abandonados', 0.2, 3),
  ((select id from categories where name = 'PINTURA'), 'Fachada sin desprendimiento o manchas', 0.2, 0),
  ((select id from categories where name = 'PINTURA'), 'Paredes interiores sin daños evidentes ni suciedad acumulada', 0.5, 1),
  ((select id from categories where name = 'PINTURA'), 'Líneas de tráfico y de segmentación visibles, y en buenas condiciones', 0.3, 2),
  ((select id from categories where name = 'MOB'), 'A/AC funciona correctamente; filtros limpios y sin fuga de refrigerante', 0.05, 0),
  ((select id from categories where name = 'MOB'), 'Mobiliario de oficina en buen estado (sin roturas o piezas faltantes)', 0.3, 1),
  ((select id from categories where name = 'MOB'), 'Equipo de trabajo (impresoras, pantallas, IP, PC, etc.) sin fallas reportadas', 0.15, 2),
  ((select id from categories where name = 'MOB'), 'No hay equipo obsoleto o fuera de servicio ocupando espacio de trabajo', 0.1, 3),
  ((select id from categories where name = 'MOB'), 'Equipos (Horno, parrilla, refrigerador y/o cafetera) permanecen limpios, sin residuos o alimentos en descomposición', 0.4, 4),
  ((select id from categories where name = 'ILUMINACION'), '100% de luminarias instaladas y funcionando', 0.5, 0),
  ((select id from categories where name = 'ILUMINACION'), 'Condiciones adecuadas de iluminación en las áreas (sin intermitencia, baja visibilidad o zonas oscuras)', 0.1, 1),
  ((select id from categories where name = 'ILUMINACION'), 'Contactos y apagadores funcionan correctamente, sin cables expuestos.', 0.4, 2),
  ((select id from categories where name = 'PLOMERIA'), 'Sin fugas visibles en tuberías, llaves o conexiones en ningún área', 0.3, 0),
  ((select id from categories where name = 'PLOMERIA'), 'Sanitarios funcionales; jabón y papel disponible (dispensadores sirven)', 0.3, 1),
  ((select id from categories where name = 'PLOMERIA'), 'Sin manchas de humedad, goteras activas o salitre en techos y paredes', 0.25, 2),
  ((select id from categories where name = 'PLOMERIA'), 'Desagües sin obstrucciones y malos olores', 0.15, 3),
  ((select id from categories where name = 'EDIFICIO'), 'Pisos sin fisuras peligrosas, desniveles, materiales sueltos o baches', 0.4, 0),
  ((select id from categories where name = 'EDIFICIO'), 'Estacionamiento delimitado, señalización visible y en buen estado', 0.15, 1),
  ((select id from categories where name = 'EDIFICIO'), 'Área de comedor limpia, funcional, con instalaciones completas', 0.2, 2),
  ((select id from categories where name = 'EDIFICIO'), 'Sin materiales de construcción abandonados o áreas fuera de servicio', 0.25, 3),
  ((select id from categories where name = 'LETREROS'), 'Señaléticas de seguridad en buenas condiciones: evacuación, extintores, botiquín, etc.', 0.3, 0),
  ((select id from categories where name = 'LETREROS'), 'Señaléticas de seguridad e higiene presentes en todas las áreas de trabajo', 0.2, 1),
  ((select id from categories where name = 'LETREROS'), 'Letreros de almacen actualizados, legibles y en área designada', 0.2, 2),
  ((select id from categories where name = 'LETREROS'), 'Letreros de almacén sin decoloración, roturas o desprendimientos', 0.3, 3),
  ((select id from categories where name = 'SEGURIDAD'), 'Cámaras de vigilancia sin obstrucciones y grabación activa verificada', 0.45, 0),
  ((select id from categories where name = 'SEGURIDAD'), 'Extintores vigentes (carga al 100%, sin vencer), accesibles, visibles y con última inspección', 0.15, 1),
  ((select id from categories where name = 'SEGURIDAD'), 'Accesos controlados correctamente (puertas, candados, chapas, alarmas)', 0.4, 2),
  ((select id from categories where name = 'LOGO'), 'Rótulo exterior en buen estado: letras completas, iluminado (si aplica), sin daños visibles', 0.5, 0),
  ((select id from categories where name = 'LOGO'), 'Publicidad actual (Información vigente, sin piezas dañadas o vencidas)', 0.15, 1),
  ((select id from categories where name = 'LOGO'), 'Imagen corporativa visual correcta en lonas, publicidad, documentos, etc. (fuentes, colores, logotipo PCP)', 0.35, 2),
  ((select id from categories where name = 'PERSONAL'), 'TODO el personal porta uniforme completo, limpio y en buen estado (presentable)', 0.35, 0),
  ((select id from categories where name = 'PERSONAL'), 'Gafete de identificación visible en todos los colaboradores', 0.2, 1),
  ((select id from categories where name = 'PERSONAL'), 'Equipo de seguridad completo (calzado de seguridad, fajas, etc.) utilizado en áreas de trabajo y visita a clientes.', 0.25, 2),
  ((select id from categories where name = 'PERSONAL'), 'Presentación personal adecuada al estándar PCP (higiene, cabello, accesorios)', 0.2, 3);
